import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  wikiSidebar: [{
    type: 'autogenerated', 
    dirName: 'wiki',
  }],
};

export default sidebars;
